tasks:
  - init: npm install
    command: |
      npm run dev
      echo "starting development server..."
      export HMR_HOST=`gp url 3000`

ports:
  - port: 3000
    onOpen: open-browser
vscode:
  extensions:
    - svelte.svelte-vscode

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
